# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

description = "This site will redirect snow leopards. Or is it the other way around?"
language = "javascript"
manifest_version = 2
name = "snowleopard.pet"
